package com.ilusons.silence.ref;

import java.util.Collection;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

public class RandomEx {

	//region Sentence generator

	public static final String[] ADJECTIVES = new String[]{
			"admiring",
			"adoring",
			"agitated",
			"amazing",
			"angry",
			"awesome",
			"backstabbing",
			"berserk",
			"big",
			"boring",
			"clever",
			"cocky",
			"compassionate",
			"condescending",
			"cranky",
			"desperate",
			"determined",
			"distracted",
			"dreamy",
			"drunk",
			"ecstatic",
			"elated",
			"elegant",
			"evil",
			"fervent",
			"focused",
			"furious",
			"gigantic",
			"gloomy",
			"goofy",
			"grave",
			"happy",
			"high",
			"hopeful",
			"hungry",
			"insane",
			"jolly",
			"jovial",
			"kickass",
			"lonely",
			"loving",
			"mad",
			"modest",
			"naughty",
			"nauseous",
			"nostalgic",
			"pedantic",
			"pensive",
			"prickly",
			"reverent",
			"romantic",
			"sad",
			"serene",
			"sharp",
			"sick",
			"silly",
			"sleepy",
			"small",
			"stoic",
			"stupefied",
			"suspicious",
			"tender",
			"thirsty",
			"tiny",
			"trusting",
	};

	public static final String[] COLORS = new String[]{
			"aqua",
			"aquamarine",
			"azure",
			"beige",
			"bisque",
			"black",
			"blue",
			"brown",
			"chartreuse",
			"chocolate",
			"coral",
			"cornsilk",
			"crimson",
			"cyan",
			"dark",
			"dim",
			"fuchsia",
			"gainsboro",
			"ghostWhite",
			"gold",
			"gray",
			"green",
			"indigo",
			"ivory",
			"khaki",
			"lavender",
			"lime",
			"linen",
			"magenta",
			"maroon",
			"moccasin",
			"navy",
			"olive",
			"orange",
			"orchid",
			"peru",
			"pink",
			"plum",
			"purple",
			"red",
			"salmon",
			"sienna",
			"silver",
			"snow",
			"tan",
			"teal",
			"thistle",
			"tomato",
			"turquoise",
			"violet",
			"wheat",
			"white",
			"yellow",
	};

	public static final String[] COOL_WORDS = new String[]{
			"ace",
			"amazing",
			"astonishing",
			"astounding",
			"awe-inspiring",
			"awesome",
			"badass",
			"beautiful",
			"bedazzling",
			"bees knees",
			"best",
			"breathtaking",
			"brilliant",
			"cats meow",
			"cats pajamas",
			"classy",
			"cool",
			"dandy",
			"dazzling",
			"delightful",
			"divine",
			"doozie",
			"epic",
			"excellent",
			"exceptional",
			"exquisite",
			"extraordinary",
			"fabulous",
			"fantastic",
			"fantabulous",
			"fine",
			"finest",
			"first-class",
			"first-rate",
			"flawless",
			"funkadelic",
			"geometric",
			"glorious",
			"gnarly",
			"good",
			"grand",
			"great",
			"groovy",
			"groundbreaking",
			"hunky-dory",
			"impeccable",
			"impressive",
			"incredible",
			"kickass",
			"kryptonian",
			"laudable",
			"legendary",
			"lovely",
			"luminous",
			"magnificent",
			"majestic",
			"marvelous",
			"mathematical",
			"mind-blowing",
			"neat",
			"outstanding",
			"peachy",
			"perfect",
			"phenomenal",
			"pioneering",
			"polished",
			"posh",
			"praiseworthy",
			"premium",
			"priceless",
			"prime",
			"primo",
			"rad",
			"remarkable",
			"riveting",
			"scrumtrulescent",
			"sensational",
			"shining",
			"slick",
			"smashing",
			"solid",
			"spectacular",
			"splendid",
			"stellar",
			"striking",
			"stunning",
			"stupendous",
			"stylish",
			"sublime",
			"super",
			"super-duper",
			"super-excellent",
			"superb",
			"superior",
			"supreme",
			"sweet",
			"swell",
			"terrific",
			"tiptop",
			"top-notch",
			"transcendent",
			"tremendous",
			"ultimate",
			"unreal",
			"well-made",
			"wicked",
			"wonderful",
			"wondrous",
			"world-class"
	};

	public static String generateRandomString(final String separator, final List<String[]> lists) {
		StringBuilder sb = new StringBuilder();

		for (int i = 0; i < lists.size(); i++) {
			String[] list = lists.get(i);
			sb.append(list[ThreadLocalRandom.current().nextInt(list.length)]);
			if (i != lists.size() - 1)
				sb.append(separator);
		}

		return sb.toString();
	}

	//endregion

}
